apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: {{ .Release.Name }}
    app: {{ include "helios.fullname" . }}
  name: {{ include "helios.fullname" . }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "helios.fullname" . }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | indent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ include "helios.name" . }}
          image: "{{ .Values.deployment.image }}:{{ .Values.deployment.tag }}"
          imagePullPolicy: {{ .Values.deployment.pullPolicy }}
          ports:
            - containerPort: 8443
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: 8443
          volumeMounts:
            - name: "certs"
              mountPath: "/certs"
              readOnly: true
            - name: "helios-admission-volume"
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: "certs"
          secret:
            secretName: {{ .Values.certs.name }}
        - name: "helios-admission-volume"
          configMap:
            name: "helios-cfgmap"
  selector:
    matchLabels:
      app: {{ include "helios.fullname" . }}