apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.certs.name }}
data:
  ca.crt: {{ .Values.certs.caCert }} # root cert
  admission.crt: {{ .Values.certs.serverCertificate }}  # place server cert
  admission.key: {{ .Values.certs.serverKey }}  # place server key