apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.webhooks.validatingWebhook.name }}
webhooks:
  - name: validate.lacework.dev
    failurePolicy: {{ .Values.webhooks.failurePolicy }}
    sideEffects: "None"
    admissionReviewVersions: ["v1beta1"]
    rules:
      - operations: ["CREATE", "CONNECT"]
        apiGroups: ["apps", ""]
        apiVersions: ["*"]
        resources: ["pods", "deployments", "pods/exec"]
    clientConfig:
      caBundle: {{ .Values.webhooks.caBundle }}
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "helios.fullname" . }}
        path: "/validate"
    timeoutSeconds: 30