apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 15
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.name }}
      {{- end }}

      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        env:
          - name: LOG_LEVEL
            value: "info"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /opt/lacework/config
      volumes:
      - name: "certs"
          secret:
            secretName: lacework-proxy-scanner-certs
      - name: config-volume
        configMap:
          name: configmap-proxy-scanner
