---
kind: Service
apiVersion: v1
metadata:
  labels:
    role: {{ include "scanner.fullname" . }}
  name: {{ include "scanner.fullname" . }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - port: 443
      targetPort: 8443
